apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quickcv-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 10Gi
