apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: abhi25022004/shortify-frontend:latest 
        imagePullPolicy: Always  
        ports:
        - containerPort: 5173
        envFrom:
        - secretRef:
            name: frontend-env
