apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: recruitment-app
  labels:
    app: backend
    tier: api
spec:
  type: ClusterIP
  selector:
    app: backend
    tier: api
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  sessionAffinity: None
