apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: recruitment-app
  labels:
    app: frontend
    tier: presentation
spec:
  type: NodePort
  selector:
    app: frontend
    tier: presentation
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
