services:
  businesslens:
    build: .
    ports:
      - "5173:5173"
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server/node_modules
    env_file:
      - ./server/.env   
