# -*- coding: utf-8 -*-
"""titanicchallengeCA_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16bg-y8HQ5VpPgjfYCXvRo4oNjrKu3Hl3
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

print("Loading datasets...")
try:
    train_data = pd.read_csv('/content/train.csv')
    test_data = pd.read_csv('/content/test.csv')
    submission_example = pd.read_csv('/content/gender_submission.csv')
except FileNotFoundError:
    print("\nERROR: One or more data files (train.csv, test.csv) not found.")
    print("Please download them from the Kaggle Data tab and upload them to your Colab environment.")

    raise

print("Train data shape:", train_data.shape)
print("Test data shape:", test_data.shape)
print("\n--- Train Data Head ---")
print(train_data.head())
print("\n--- Train Data Info ---")
train_data.info()

passenger_ids = test_data['PassengerId']

y_train = train_data['Survived']
X_train = train_data.drop('Survived', axis=1)

full_data = pd.concat([X_train, test_data], axis=0, ignore_index=True)


features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']
data = full_data[features].copy()


print("\n--- Handling Missing Values ---")

data['Age'].fillna(data['Age'].median(), inplace=True)

data['Fare'].fillna(data['Fare'].median(), inplace=True)

print("Null counts after cleaning:")
print(data.isnull().sum())


print("\n--- Encoding Categorical Features ---")

data = pd.get_dummies(data, columns=['Sex'], drop_first=True)

data = pd.get_dummies(data, columns=['Pclass'], prefix='Pclass')


X_train_cleaned = data.iloc[:len(X_train)]
X_test_cleaned = data.iloc[len(X_train):]

X_train_final = X_train_cleaned.drop(['Sex'], axis=1, errors='ignore')
X_test_final = X_test_cleaned.drop(['Sex'], axis=1, errors='ignore')


print("\n--- Training Logistic Regression Model ---")
model = LogisticRegression(solver='liblinear', random_state=42)

model.fit(X_train_final, y_train)

y_train_pred = model.predict(X_train_final)
train_accuracy = accuracy_score(y_train, y_train_pred)
print(f"Training Accuracy: {train_accuracy:.4f}")

predictions = model.predict(X_test_final)



print("\n--- Generating Submission File ---")

submission_df = pd.DataFrame({
    'PassengerId': passenger_ids,
    'Survived': predictions
})

submission_df['Survived'] = submission_df['Survived'].astype(int)

submission_file_name = 'titanic_submission_colab.csv'
submission_df.to_csv(submission_file_name, index=False)

print(f"\n Submission file '{submission_file_name}' successfully created!")
print(submission_df.head())