---
- name: Configure runtime environment for Face Film Finder
  hosts: webservers
  become: yes
  vars:
    app_user: facefilm
    app_dir: /opt/face-film-finder
    python_version: "3.9"

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Python and pip
      apt:
        name:
          - python{{ python_version }}
          - python{{ python_version }}-pip
          - python{{ python_version }}-venv
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present
      when: ansible_os_family == 'Debian'

    - name: Create application user
      user:
        name: "{{ app_user }}"
        system: yes
        shell: /bin/bash
        home: "{{ app_dir }}"
        create_home: yes

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: Copy project files
      copy:
        src: ../
        dest: "{{ app_dir }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
      ignore_errors: yes

    - name: Install Python dependencies
      pip:
        requirements: "{{ app_dir }}/backend/requirements.txt"
        virtualenv: "{{ app_dir }}/venv"
        virtualenv_python: python{{ python_version }}

    - name: Install Node.js dependencies
      npm:
        path: "{{ app_dir }}"
        state: present

    - name: Build frontend
      command: npm run build
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    - name: Set permissions for models
      file:
        path: "{{ app_dir }}/backend/models"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        recurse: yes
