---
- name: Retrieve Jenkins initial admin password
  hosts: jenkins
  become: yes

  tasks:
    - name: Get initial Jenkins admin password
      command: docker exec jenkins-docker cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_password

    - name: Show Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"
