---
- name: restart microplastic app
  systemd:
    name: microplastic-app
    state: restarted
    daemon_reload: yes

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded