apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-app-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: node-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http-metrics  # This matches the Service port name
      path: /metrics
      interval: 15s
      scheme: http
