name: Full Stack CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      
      - name: Create .env file
        run: |
          cat << EOF > .env
          JWT_SECRET=test_secret_for_ci
          GOOGLE_CLIENT_ID=test_client_id
          JUDGE0_API_KEY=test_judge0_key
          GOOGLE_API_KEY=test_gemini_key
          GEMINI_API_KEY=test_gemini_key
          MONGO_URI=mongodb://mongo:27017/recruitment
          PORT=5000
          NODE_ENV=test
          EOF
      
      - name: Build containers
        run: docker-compose build
      
      - name: Start services
        run: docker-compose up -d
      
      - name: Wait for services
        run: |
          echo "Waiting for services to start..."
          sleep 45
      
      - name: Check container status
        run: docker-compose ps
      
      - name: Test backend health
        run: |
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:5000/ || exit 1
      
      - name: Show logs on failure
        if: failure()
        run: docker-compose logs
      
      - name: Cleanup
        if: always()
        run: docker-compose down -v

  push-images:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    continue-on-error: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      
      - name: Build and push backend
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            gkarthick010/devops_trail-backend:latest
            gkarthick010/devops_trail-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            gkarthick010/devops_trail-frontend:latest
            gkarthick010/devops_trail-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
