apiVersion: apps/v1
kind: Deployment
metadata:
  name: microplastic-classifier
  namespace: microplastic-app
  labels:
    app: microplastic-classifier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microplastic-classifier
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: microplastic-classifier
    spec:
      containers:
      - name: microplastic-classifier
        image: microplastic-detector:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        env:
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: microplastic-classifier-service
  namespace: microplastic-app
spec:
  selector:
    app: microplastic-classifier
  ports:
  - port: 80
    targetPort: 8501
  type: LoadBalancer