apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wealthwise-backend-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: wealthwise-backend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
