name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./mern-server  # make sure npm install runs in backend folder

      # Optional: skip tests if you don't have them
      # - name: Run tests
      #   run: npm test
      #   working-directory: ./mern-server

      - name: Build Backend Docker image
        run: docker build -t shilpibiswal/flexibook-backend:${{ github.sha }} ./mern-server

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push shilpibiswal/flexibook-backend:${{ github.sha }}




